### ISSUE TITLE
<ConversationNotification> - mentioned on the notif-handler sample in readme - cannot be resolved

### ISSUE THREAD

**Issue by dmytro-zelenskyy** [MyPureCloud/platform-client-sdk-dotnet#3]
<ConversationNotification> - mentioned on the notif-handler sample in readme - cannot be resolved

search does not help :-()
-----------------------
           else if (data.GetType() == typeof(NotificationData<ConversationNotification>))
                            {
                                var conversation = (NotificationData<ConversationNotification>)data;
                                Console.WriteLine($"Conversation: {conversation.EventBody.Id}");
                            }

**Comment by timsmithgenesys** [comment]
Hello, I'm not sure what you're asking here. Could you create a new post on the Genesys Cloud Developer Forum with details about what you're trying to do and what problems you're facing? Thanks!

https://developer.mypurecloud.com/forum/c/platform-api/dot-net-sdk/
